# Generated by Django 4.1.4 on 2022-12-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.URLField(default='https://example.com/default_image.jpg'),
        ),
    ]
