# Generated by Django 4.1.4 on 2022-12-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_image'),
    ]

    operations = [
    ]
